// 0 = path, 1 = wall
export const mazeMap = [
  [1,1,1,1,1,1,1,1,1,1],
  [1,0,0,0,1,0,0,0,0,1],
  [1,0,1,0,1,0,1,1,0,1],
  [1,0,1,0,0,0,0,1,0,1],
  [1,0,1,1,1,1,0,1,0,1],
  [1,0,0,0,0,1,0,1,0,1],
  [1,1,1,1,0,1,0,1,0,1],
  [1,0,0,1,0,0,0,0,0,1],
  [1,1,0,0,0,1,1,1,0,1],
  [1,1,1,1,1,1,1,1,1,1],
];

export const services = [
  { id: "Dataset", name: "Dataset", icon: "📊", color: "bg-blue-500" },
  { id: "Model", name: "Model", icon: "🧠", color: "bg-purple-500" },
  { id: "Training", name: "Training", icon: "🏋️", color: "bg-green-500" },
  { id: "Inference", name: "Inference", icon: "🔮", color: "bg-orange-500" },
  { id: "Preprocessing", name: "Preprocessing", icon: "🔧", color: "bg-yellow-500" },
  { id: "Evaluation", name: "Evaluation", icon: "📈", color: "bg-red-500" },
];

export const aiLessons = [
  {
    id: 1,
    title: "Introduction to AI",
    quizzes: [
      { q: "What is Artificial Intelligence?", options: ["Machines performing tasks that typically require human intelligence", "A type of computer hardware", "A programming language", "A database system"], correct: 0 },
      { q: "What is Machine Learning?", options: ["A subset of AI where systems learn from data", "A way to write code", "A type of computer", "A storage device"], correct: 0 },
    ],
  },
  {
    id: 2,
    title: "Neural Networks Basics",
    quizzes: [
      { q: "What is a neural network?", options: ["A computing system inspired by biological neural networks", "A type of database", "A programming framework", "A cloud service"], correct: 0 },
      { q: "What are neurons in AI?", options: ["Basic units that process information", "Types of data", "Programming functions", "Hardware components"], correct: 0 },
    ],
  },
];

export const quests = [
  {
    id: 1,
    title: "Introduction to AI",
    description: "Learn the fundamentals of Artificial Intelligence and its basic concepts.",
    requiredServices: ["Dataset", "Model", "Training"],
    requiredConnections: [["Dataset", "Model"], ["Model", "Training"]],
    quizzes: [
      { q: "What is Artificial Intelligence?", options: ["Machines performing tasks that typically require human intelligence", "A type of computer hardware", "A programming language", "A database system"], correct: 0 },
      { q: "Which of these is NOT a type of AI?", options: ["Narrow AI", "General AI", "Super AI", "Artificial AI"], correct: 3 },
      { q: "What does AI stand for?", options: ["Automated Intelligence", "Artificial Intelligence", "Advanced Integration", "Algorithmic Interface"], correct: 1 },
      { q: "Which field is considered the foundation of AI?", options: ["Computer Science", "Mathematics", "Physics", "Chemistry"], correct: 0 },
      { q: "What is machine learning?", options: ["A type of computer", "A programming language", "A subset of AI where systems learn from data", "A hardware component"], correct: 2 },
      { q: "What is deep learning?", options: ["Learning from books", "A subset of machine learning using neural networks", "Learning foreign languages", "A type of database"], correct: 1 },
      { q: "Which company developed the first AI program?", options: ["Google", "Microsoft", "IBM", "Apple"], correct: 2 },
      { q: "What is natural language processing?", options: ["Processing natural foods", "AI understanding human language", "Processing computer code", "A type of database"], correct: 1 },
      { q: "What is computer vision?", options: ["A computer screen", "AI interpreting visual information", "A type of monitor", "Computer graphics"], correct: 1 },
      { q: "What is the goal of AI?", options: ["To replace all human jobs", "To create intelligent machines that can think and learn", "To build faster computers", "To develop new programming languages"], correct: 1 },
    ],
  },
  {
    id: 2,
    title: "Machine Learning Fundamentals",
    description: "Explore the core concepts of machine learning algorithms and techniques.",
    requiredServices: ["Preprocessing", "Dataset", "Model", "Training", "Inference"],
    requiredConnections: [["Preprocessing", "Dataset"], ["Dataset", "Model"], ["Model", "Training"], ["Training", "Inference"]],
    quizzes: [
      { q: "What is supervised learning?", options: ["Learning without any guidance", "Learning with labeled training data", "Learning from mistakes only", "Learning randomly"], correct: 1 },
      { q: "What is unsupervised learning?", options: ["Learning with teacher supervision", "Learning from unlabeled data", "Learning from books", "Learning with full guidance"], correct: 1 },
      { q: "What is reinforcement learning?", options: ["Learning through trial and error with rewards", "Learning from labeled data", "Learning from books", "Learning without data"], correct: 0 },
      { q: "What is a training set?", options: ["A set of test questions", "Data used to train the model", "A computer program", "A type of algorithm"], correct: 1 },
      { q: "What is overfitting?", options: ["When model performs well on training data but poorly on new data", "When model performs poorly on training data", "When model trains too slowly", "When model uses too little data"], correct: 0 },
      { q: "What is underfitting?", options: ["When model is too complex", "When model is too simple and doesn't capture patterns", "When model trains too fast", "When model has too much data"], correct: 1 },
      { q: "What is cross-validation?", options: ["Validating across different countries", "Technique to evaluate model performance", "A type of algorithm", "A programming method"], correct: 1 },
      { q: "What is a confusion matrix?", options: ["A matrix of confused numbers", "Table showing prediction accuracy", "A type of error", "A mathematical formula"], correct: 1 },
      { q: "What is feature engineering?", options: ["Building new features from existing data", "Designing computer hardware", "Writing code", "Creating databases"], correct: 0 },
      { q: "What is the bias-variance tradeoff?", options: ["Choosing between different biases", "Balancing model complexity and generalization", "A type of algorithm", "A programming concept"], correct: 1 },
    ],
  },
  {
    id: 3,
    title: "Neural Networks",
    description: "Dive deep into neural network architecture and how they learn.",
    requiredServices: ["Dataset", "Model", "Training", "Inference", "Evaluation"],
    requiredConnections: [["Dataset", "Model"], ["Model", "Training"], ["Training", "Inference"], ["Inference", "Evaluation"]],
    quizzes: [
      { q: "What is a neuron in neural networks?", options: ["A brain cell", "Basic computational unit that processes information", "A type of computer", "A programming language"], correct: 1 },
      { q: "What is an activation function?", options: ["A function that activates the computer", "Function that determines neuron output", "A type of input", "A programming function"], correct: 1 },
      { q: "What is backpropagation?", options: ["Moving backwards in time", "Algorithm to train neural networks", "A type of error", "A mathematical method"], correct: 1 },
      { q: "What is a hidden layer?", options: ["A secret computer layer", "Layers between input and output", "A type of algorithm", "A programming concept"], correct: 1 },
      { q: "What is gradient descent?", options: ["Descending a mountain", "Optimization algorithm to minimize loss", "A type of error", "A mathematical formula"], correct: 1 },
      { q: "What is a convolutional neural network (CNN)?", options: ["A network for conversations", "Network designed for image processing", "A type of computer", "A programming framework"], correct: 1 },
      { q: "What is a recurrent neural network (RNN)?", options: ["A repeating network", "Network with memory for sequences", "A type of algorithm", "A programming method"], correct: 1 },
      { q: "What is the vanishing gradient problem?", options: ["Gradients disappearing during training", "A type of error", "A mathematical issue", "A programming bug"], correct: 0 },
      { q: "What is batch normalization?", options: ["Normalizing data in batches", "Technique to stabilize training", "A type of algorithm", "A programming method"], correct: 1 },
      { q: "What is transfer learning?", options: ["Moving data between computers", "Using pre-trained models for new tasks", "A type of error", "A programming concept"], correct: 1 },
    ],
  },
  {
    id: 4,
    title: "Computer Vision",
    description: "Learn how AI can see and understand visual information.",
    requiredServices: ["Dataset", "Model", "Training", "Inference", "Evaluation"],
    requiredConnections: [["Dataset", "Model"], ["Model", "Training"], ["Training", "Inference"], ["Inference", "Evaluation"]],
    quizzes: [
      { q: "What is image classification?", options: ["Sorting images by size", "Assigning labels to images", "A type of computer", "A programming method"], correct: 1 },
      { q: "What is object detection?", options: ["Finding objects in images", "Detecting computer viruses", "A type of algorithm", "A programming concept"], correct: 0 },
      { q: "What is image segmentation?", options: ["Dividing images into segments", "Cutting images into pieces", "A type of error", "A mathematical method"], correct: 0 },
      { q: "What is a pixel?", options: ["A type of computer", "Smallest unit of a digital image", "A programming language", "A type of algorithm"], correct: 1 },
      { q: "What is edge detection?", options: ["Finding image boundaries", "Detecting computer edges", "A type of error", "A programming method"], correct: 0 },
      { q: "What is image preprocessing?", options: ["Processing images before analysis", "A type of computer", "A programming concept", "A mathematical formula"], correct: 0 },
      { q: "What is optical character recognition (OCR)?", options: ["Reading text from images", "A type of camera", "A programming language", "A type of algorithm"], correct: 0 },
      { q: "What is facial recognition?", options: ["Recognizing faces in images", "A type of mirror", "A programming method", "A mathematical concept"], correct: 0 },
      { q: "What is image augmentation?", options: ["Making images bigger", "Techniques to increase dataset size", "A type of error", "A programming concept"], correct: 1 },
      { q: "What is a bounding box?", options: ["A box for storage", "Rectangle around detected objects", "A type of computer", "A programming method"], correct: 1 },
    ],
  },
  {
    id: 5,
    title: "Natural Language Processing",
    description: "Discover how AI understands and generates human language.",
    requiredServices: ["Dataset", "Model", "Training", "Inference", "Evaluation"],
    requiredConnections: [["Dataset", "Model"], ["Model", "Training"], ["Training", "Inference"], ["Inference", "Evaluation"]],
    quizzes: [
      { q: "What is tokenization?", options: ["Breaking text into smaller units", "A type of computer", "A programming method", "A mathematical formula"], correct: 0 },
      { q: "What is sentiment analysis?", options: ["Analyzing computer performance", "Determining emotional tone of text", "A type of algorithm", "A programming concept"], correct: 1 },
      { q: "What is named entity recognition?", options: ["Recognizing famous people", "Identifying names, dates, locations in text", "A type of computer", "A programming method"], correct: 1 },
      { q: "What is part-of-speech tagging?", options: ["Tagging parts for sale", "Assigning grammatical categories to words", "A type of error", "A mathematical method"], correct: 1 },
      { q: "What is text classification?", options: ["Sorting text by size", "Categorizing text into predefined classes", "A type of computer", "A programming concept"], correct: 1 },
      { q: "What is machine translation?", options: ["Translating between programming languages", "Automatic translation between human languages", "A type of computer", "A mathematical formula"], correct: 1 },
      { q: "What is a language model?", options: ["A model of a language", "Statistical model predicting word sequences", "A type of computer", "A programming method"], correct: 1 },
      { q: "What is word embedding?", options: ["Embedding words in books", "Representing words as vectors", "A type of error", "A programming concept"], correct: 1 },
      { q: "What is text summarization?", options: ["Making text shorter", "Creating concise summaries of longer text", "A type of computer", "A mathematical method"], correct: 1 },
      { q: "What is question answering?", options: ["Asking questions to computers", "Systems that answer questions from text", "A type of algorithm", "A programming concept"], correct: 1 },
    ],
  },
];